name: 'Push a directory to another repository'
description: 'Used for pushing a copy of a folder to another repository'
inputs:
  source_folder:
    description: 'Source folder from the origin directory'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Directory to push the folder contents to'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push folder to, defaults to master'
    required: false
  commit_msg:
    description: 'The commit message'
    required: false
  destination_branch_create:
    description: 'Destination branch to create for this commit'
    required: false
  clean_files:
    description: 'Clean these files from source brfore push and commit'
    required: false
  debug:
    description: 'Used to debug content'
    required: false
runs:
  using: 'composite'
  steps:
      - run: apt-get update && apt-get install -y git
        shell: 
      - run: ${{ github.action_path }}/setup.sh
        shell: 
        name: Setup
      - run: ${{ github.action_path }}/clean.sh
        shell: 
        name: Clean
      - run: ${{ github.action_path }}/move.sh
        shell: 
        name: move
      - run: ${{ github.action_path }}/commit.sh
        shell: 
        name: commit
branding:
  icon: 'git-commit'
  color: 'green'
