## Source: https://github.com/marketplace/actions/push-a-directory-to-another-repository

name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes source files
      uses: ./.github/actions/
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './'
        destination_repo: 'gh4-io/charts'
        destination_branch: 'master'
        destination_folder: 'charts/papermerge'
        user_email: 'jason@gh4.io'
        user_name: 'gh4-io'
        commit_msg: 'Push post update'
        clean_files: '.git,.git*,.vscode,*.tgz,.values*'
        debug: false
